In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(color_codes=True)
import pandas as pd
%matplotlib inline

In [25]:
#Reading the dataset
df = pd.read_csv('taskrabbit.csv')
df.head() # This command will give top 5 rows of dataset, just to check if everything loaded correct.

,recommendation_id,created_at,tasker_id,position,hourly_rate,num_completed_tasks,hired,category
0,0-0-70cf97d7-37af-4834-901c-ce3ad4893b8c,2017-09-01 00:32:25,1009185352,1,38,151,0,Furniture Assembly
1,0-0-70cf97d7-37af-4834-901c-ce3ad4893b8c,2017-09-01 00:32:25,1006892359,2,40,193,0,Furniture Assembly
2,0-0-70cf97d7-37af-4834-901c-ce3ad4893b8c,2017-09-01 00:32:25,1012023956,3,28,0,0,Furniture Assembly
3,0-0-70cf97d7-37af-4834-901c-ce3ad4893b8c,2017-09-01 00:32:25,1009733517,4,43,303,0,Furniture Assembly
4,0-0-70cf97d7-37af-4834-901c-ce3ad4893b8c,2017-09-01 00:32:25,1013579273,5,29,39,0,Furniture Assembly

In [26]:
#Check if there is any Null Values in dataset
#Data Preprocessing

print(df.isnull().sum()) # Check for Null Values in all columns,there is no null values.
print('*'* 60)
print(df.shape)  #Check number of rows and columns.

recommendation_id      0
created_at             0
tasker_id              0
position               0
hourly_rate            0
num_completed_tasks    0
hired                  0
category               0
dtype: int64
************************************************************
(30000, 8)

In [27]:
#Q1. How many recommendation sets are in this data sample?
print(df['recommendation_id'].nunique())

2100

In [5]:
# 2. Each recommendation set shows from 1 to 15 Taskers, what is:
     # 2.1 average number of Taskers shown
data = df.drop(["created_at","hourly_rate","num_completed_tasks","hired","category"],axis=1)    
data.groupby('recommendation_id').agg(np.mean)

                                                   tasker_id  position
recommendation_id
0-0-00033225-3f89-47dd-b4f1-5d1feb359a76        1.012351e+09  8.000000
0-0-000ea7f0-2ad9-48ee-bc79-899ee439be82        1.010879e+09  8.000000
0-0-0027ac52-1983-4130-8a65-5048dda560c9        1.012065e+09  8.000000
0-0-003a3672-3c80-4134-b409-b80baee0e082        1.010516e+09  8.000000
0-0-0045d200-f7c0-4fe6-94df-b89a4cde3ee7        1.011035e+09  8.000000
0-0-0046a0f0-1d70-42e4-a6d3-43e9a4c614d9        1.010718e+09  8.000000
0-0-004cc112-d2ee-4753-8e55-76e95369364e        1.010937e+09  8.000000
0-0-00549753-28f1-4291-b176-e1bec0d77b0e        1.010635e+09  8.000000
0-0-006326c7-5448-48fe-8e08-55d0fdfb9fe2        1.011008e+09  8.000000
0-0-006fe8d8-309a-4f2f-ae14-2936321fc19d        1.011060e+09  8.000000
0-0-00b95cf0-4601-4123-b9af-cd4fe12c3f7f        1.009753e+09  8.000000
0-0-00ce31c0-5231-4513-aa89-6c4728302d3a        1.010409e+09  8.000000
0-0-00de637e-d409-43dc-9548-5256a6d0da08        1.010807e+09  8.000000
0-0-0106fbd0-cacb-486e-9784-5b2ce3413d4d        1.010644e+09  8.000000
0-0-0113ae83-4f0d-4486-9d43-07d3de2c4379        1.011742e+09  8.000000
0-0-012a6b39-0631-422a-b85e-bf8042219b81        1.009965e+09  8.000000
0-0-0144bfba-51c4-4908-b81e-dd6f6d6585d4        1.010874e+09  8.000000
0-0-015ecb45-b756-4600-9832-bcc64a9418b5        1.010217e+09  8.000000
0-0-0167f1c8-f9d3-4864-9966-546cf9301356        1.009882e+09  8.000000
0-0-017a766c-f9dc-4a35-b9c7-4dee23699baf        1.011214e+09  8.000000
0-0-01899589-bb55-4423-80bf-cf4894256428        1.010073e+09  4.500000
0-0-01b1517c-f961-4d79-940d-5ea9af00e909        1.012020e+09  8.000000
0-0-01bbfb8b-57d5-4b6a-ab7c-f5afef8e5601        1.010796e+09  8.000000
0-0-01c651df-ae33-4eeb-8195-ffae2dddebc7        1.011298e+09  8.000000
0-0-01efc167-42d0-43fb-b425-828a085c27ae        1.010329e+09  8.000000
0-0-02018374-9741-44d6-828b-c1e6405917be        1.011072e+09  8.000000
0-0-021e6b13-7bea-4d64-9174-a1c44d3c2d3f        1.011928e+09  8.000000
0-0-022aa795-27a3-4062-8f9f-391ced0163cc        1.010474e+09  8.000000
0-0-023e0acd-2ef3-402f-8e9f-2236f4b95f4a        1.010523e+09  5.000000
0-0-02563b70-29bc-4ca8-b591-a4565da162a0        1.009644e+09  8.000000
...                                                      ...       ...
0-0-f83a696c-70f7-46b2-bce0-ea426df9ec80        1.010295e+09  8.000000
0-0-f87f4146-5d5b-45d2-82a0-bb73729c44ee        1.010361e+09  8.000000
0-0-f89bf915-9d48-4493-9efa-11e72230bbf7        1.009229e+09  8.000000
0-0-f8db240a-66f2-49d3-a8ce-8d1810173a4e        1.011270e+09  8.000000
0-0-f939965e-0c4f-42be-b1ae-2bd27855b5d9        1.011786e+09  8.000000
0-0-f99f28ef-49ef-4cf2-bc46-41e32f8166bd        1.013609e+09  2.000000
0-0-fa4e51ef-25fe-4744-8c9b-965e2170eac4        1.010470e+09  8.000000
0-0-fad5f743-c241-4f7f-9899-9da519fd6f4e        1.010052e+09  8.000000
0-0-faf15dd8-ab06-4d83-83ee-f1c11df750dd        1.010289e+09  8.000000
0-0-fb2845ff-6d1b-4cb9-a5f7-670decb70510        1.010181e+09  8.000000
0-0-fb5142bc-76a0-423b-aa3b-dfefe959405d        1.010706e+09  8.000000
0-0-fc90aed8-586e-45a0-b8a8-d86101d0c474        1.011293e+09  8.000000
0-0-fcfc3872-1335-4fe3-ab5f-a2455ffd39f7        1.010780e+09  8.000000
0-0-fe29c383-d127-4344-8b76-5030d72c73bf        1.011052e+09  8.000000
0-0-ff1ec648-00d9-4ac8-ad5c-6cf8a49e570c        1.011088e+09  8.000000
0-0-ff88d5b0-7977-4cb5-9fed-a757670a3ce1        1.011857e+09  8.000000
0-1078833-0c4df1de-8fd1-41f6-93b6-3fc8cc280318  1.010861e+09  8.000000
0-1078833-1d4e2af9-40ef-4d5a-af46-1f3323781e0b  1.010861e+09  8.000000
0-1078833-21a12397-907b-435a-ba4a-1960bb493c45  1.010421e+09  8.000000
0-1078833-2bf68196-0107-4253-9c23-19d45d94413f  1.010394e+09  8.000000
0-1078833-2fcc37f5-1beb-4cbb-99b9-c68ff2f58a1d  1.010905e+09  8.000000
0-1078833-389b5181-77d2-4393-87b4-254ddfcb4e1a  1.011090e+09  8.000000
0-1078833-3a488665-f9d0-489f-b46a-2e8e26c1fc85  1.011172e+09  8.000000
0-1078833-47012ad9-ca2e-4644-9196-dc90be99b4c0  1.010763e+09  8.000000
0-1078833-52edd4ef-15a7-4899-a60a-2518a8db8646  1.011155e+09  8.000000
0-1078833-533e288a-39c8-4721-8c5b-5b9fe472d478  1.010791e+09  8.000000
0-1078833-54d459fd-bb51-40fd-88bf-62ab8dfc8d77  1.010467e+09  8.000000
0-1078833-569d76c9-681f-4ed6-92e6-0a0942a3ac76  1.010791e+09  8.000000
0-1078833-593326fc-d192-46b5-98ca-c2797929c27a  1.011188e+09  8.000000
0-1078833-59ab55bd-23e9-416c-aa71-6b277859ca2d  1.010028e+09  8.777778

[2100 rows x 2 columns]

In [28]:
#Q2.2 median number of Taskers shown
data.groupby('recommendation_id').agg(np.median)

                                                   tasker_id  position
recommendation_id
0-0-00033225-3f89-47dd-b4f1-5d1feb359a76        1.013330e+09       8.0
0-0-000ea7f0-2ad9-48ee-bc79-899ee439be82        1.010214e+09       8.0
0-0-0027ac52-1983-4130-8a65-5048dda560c9        1.012721e+09       8.0
0-0-003a3672-3c80-4134-b409-b80baee0e082        1.009114e+09       8.0
0-0-0045d200-f7c0-4fe6-94df-b89a4cde3ee7        1.010353e+09       8.0
0-0-0046a0f0-1d70-42e4-a6d3-43e9a4c614d9        1.009838e+09       8.0
0-0-004cc112-d2ee-4753-8e55-76e95369364e        1.009966e+09       8.0
0-0-00549753-28f1-4291-b176-e1bec0d77b0e        1.009916e+09       8.0
0-0-006326c7-5448-48fe-8e08-55d0fdfb9fe2        1.010540e+09       8.0
0-0-006fe8d8-309a-4f2f-ae14-2936321fc19d        1.010214e+09       8.0
0-0-00b95cf0-4601-4123-b9af-cd4fe12c3f7f        1.009585e+09       8.0
0-0-00ce31c0-5231-4513-aa89-6c4728302d3a        1.009607e+09       8.0
0-0-00de637e-d409-43dc-9548-5256a6d0da08        1.009704e+09       8.0
0-0-0106fbd0-cacb-486e-9784-5b2ce3413d4d        1.009700e+09       8.0
0-0-0113ae83-4f0d-4486-9d43-07d3de2c4379        1.012043e+09       8.0
0-0-012a6b39-0631-422a-b85e-bf8042219b81        1.009431e+09       8.0
0-0-0144bfba-51c4-4908-b81e-dd6f6d6585d4        1.009592e+09       8.0
0-0-015ecb45-b756-4600-9832-bcc64a9418b5        1.009544e+09       8.0
0-0-0167f1c8-f9d3-4864-9966-546cf9301356        1.009114e+09       8.0
0-0-017a766c-f9dc-4a35-b9c7-4dee23699baf        1.011940e+09       8.0
0-0-01899589-bb55-4423-80bf-cf4894256428        1.009393e+09       4.5
0-0-01b1517c-f961-4d79-940d-5ea9af00e909        1.013360e+09       8.0
0-0-01bbfb8b-57d5-4b6a-ab7c-f5afef8e5601        1.009698e+09       8.0
0-0-01c651df-ae33-4eeb-8195-ffae2dddebc7        1.010050e+09       8.0
0-0-01efc167-42d0-43fb-b425-828a085c27ae        1.009700e+09       8.0
0-0-02018374-9741-44d6-828b-c1e6405917be        1.010214e+09       8.0
0-0-021e6b13-7bea-4d64-9174-a1c44d3c2d3f        1.012721e+09       8.0
0-0-022aa795-27a3-4062-8f9f-391ced0163cc        1.009592e+09       8.0
0-0-023e0acd-2ef3-402f-8e9f-2236f4b95f4a        1.009645e+09       5.0
0-0-02563b70-29bc-4ca8-b591-a4565da162a0        1.009168e+09       8.0
...                                                      ...       ...
0-0-f83a696c-70f7-46b2-bce0-ea426df9ec80        1.009618e+09       8.0
0-0-f87f4146-5d5b-45d2-82a0-bb73729c44ee        1.009998e+09       8.0
0-0-f89bf915-9d48-4493-9efa-11e72230bbf7        1.009226e+09       8.0
0-0-f8db240a-66f2-49d3-a8ce-8d1810173a4e        1.011946e+09       8.0
0-0-f939965e-0c4f-42be-b1ae-2bd27855b5d9        1.011998e+09       8.0
0-0-f99f28ef-49ef-4cf2-bc46-41e32f8166bd        1.014158e+09       2.0
0-0-fa4e51ef-25fe-4744-8c9b-965e2170eac4        1.009647e+09       8.0
0-0-fad5f743-c241-4f7f-9899-9da519fd6f4e        1.009542e+09       8.0
0-0-faf15dd8-ab06-4d83-83ee-f1c11df750dd        1.010050e+09       8.0
0-0-fb2845ff-6d1b-4cb9-a5f7-670decb70510        1.009348e+09       8.0
0-0-fb5142bc-76a0-423b-aa3b-dfefe959405d        1.009647e+09       8.0
0-0-fc90aed8-586e-45a0-b8a8-d86101d0c474        1.011968e+09       8.0
0-0-fcfc3872-1335-4fe3-ab5f-a2455ffd39f7        1.010258e+09       8.0
0-0-fe29c383-d127-4344-8b76-5030d72c73bf        1.009549e+09       8.0
0-0-ff1ec648-00d9-4ac8-ad5c-6cf8a49e570c        1.010402e+09       8.0
0-0-ff88d5b0-7977-4cb5-9fed-a757670a3ce1        1.012039e+09       8.0
0-1078833-0c4df1de-8fd1-41f6-93b6-3fc8cc280318  1.010008e+09       8.0
0-1078833-1d4e2af9-40ef-4d5a-af46-1f3323781e0b  1.010008e+09       8.0
0-1078833-21a12397-907b-435a-ba4a-1960bb493c45  1.009606e+09       8.0
0-1078833-2bf68196-0107-4253-9c23-19d45d94413f  1.009559e+09       8.0
0-1078833-2fcc37f5-1beb-4cbb-99b9-c68ff2f58a1d  1.010008e+09       8.0
0-1078833-389b5181-77d2-4393-87b4-254ddfcb4e1a  1.010567e+09       8.0
0-1078833-3a488665-f9d0-489f-b46a-2e8e26c1fc85  1.010611e+09       8.0
0-1078833-47012ad9-ca2e-4644-9196-dc90be99b4c0  1.009998e+09       8.0
0-1078833-52edd4ef-15a7-4899-a60a-2518a8db8646  1.010624e+09       8.0
0-1078833-533e288a-39c8-4721-8c5b-5b9fe472d478  1.010258e+09       8.0
0-1078833-54d459fd-bb51-40fd-88bf-62ab8dfc8d77  1.009544e+09       8.0
0-1078833-569d76c9-681f-4ed6-92e6-0a0942a3ac76  1.010258e+09       8.0
0-1078833-593326fc-d192-46b5-98ca-c2797929c27a  1.010624e+09       8.0
0-1078833-59ab55bd-23e9-416c-aa71-6b277859ca2d  1.009606e+09       9.0

[2100 rows x 2 columns]

In [7]:
#Q3. How many total unique Taskers are there in this data sample?
print(df['tasker_id'].nunique())

830

In [29]:
#Q4 #4.1 Which Tasker has been shown the most? 
#Ans: 1014508755 

#Q4  #4.2 Which Tasker has been shown the least?
#Ans: There ar many taskers who have appeard only once, check the output below.

df.tasker_id.value_counts()

1014508755    608
1012043028    438
1014675294    387
1014629676    311
1015015238    290
1008887321    290
1007283421    290
1006892359    280
1008831520    277
1012721277    269
1014157578    262
1014423146    260
1013283344    227
1013307670    225
1007737526    218
1013794735    215
1009226132    209
1014315490    207
1009185352    203
1007081910    198
1013760262    194
1008839858    193
1013229872    190
1009604120    185
1009114267    182
1009062537    181
1013131759    181
1013443601    179
1009530281    179
1013165984    178
             ...
1009772528      1
1014478773      1
1009754999      1
1008919567      1
1008368716      1
1013854788      1
1013656032      1
1013731883      1
1013362004      1
1010042971      1
1007246122      1
1011952623      1
1009547227      1
1008033678      1
1012805440      1
1007472083      1
1009618500      1
1011985968      1
1009702351      1
1007638825      1
1009712638      1
1007480912      1
1008870833      1
1010640007      1
1014593279      1
1014086818      1
1008474216      1
1012151299      1
1014439502      1
1011972750      1
Name: tasker_id, Length: 830, dtype: int64

In [30]:
#Q5, 5.1 Which Tasker has been hired the most?   Ans: 1015020347
print(df['tasker_id'][df['hired'] == 1].max())

print('*'* 60)

#Q5, 5.2 Which Tasker has been hired the least?  Ans: 1006648538
print(df['tasker_id'][df['hired'] == 1].min())

1015020347
************************************************************
1006648538

In [31]:
#Total number of taskers hired and not hired

df['hired'].value_counts()

0    28295
1     1705
Name: hired, dtype: int64

In [32]:
#Q6. If we define the "Tasker conversion rate" as the number of times a
   #Tasker has been hired, out of the number of times the Tasker has
   #been shown, how many Taskers have a conversion rate of 100%

x = df.loc[df['hired']==0]
u_x = x.tasker_id.unique()
u_df = df.tasker_id.unique()
print(np.setdiff1d(u_df , u_x))

[1007480912 1008094420 1008861741 1011985968 1012369686 1014478773]

In [ ]:
#Q7 The conversion rate of 100% for all taskers is not happening in this data set but it will depend on various factors like
#   hourly_rate, num_completed_tasks, category etc.

In [33]:
#Q8. For each category, what is the average position of the Tasker who is hired?

df.groupby(['category','hired']).mean()

                             tasker_id  position  hourly_rate  \
category           hired
Furniture Assembly 0      1.010970e+09  8.139054    39.463301
                   1      1.010678e+09  3.611888    38.701049
Mounting           0      1.011415e+09  8.065586    50.493961
                   1      1.011709e+09  4.596085    50.154804
Moving Help        0      1.010815e+09  8.095662    83.736345
                   1      1.011096e+09  4.145359    63.012259

                          num_completed_tasks
category           hired
Furniture Assembly 0               182.000212
                   1               249.020979
Mounting           0               216.470227
                   1               284.096085
Moving Help        0               256.616608
                   1               273.882662

In [34]:
#Q9. For each category, what is the average hourly rate and average number of completed tasks for the Taskers who are hired?
df.groupby(['category','hired']).mean()

                             tasker_id  position  hourly_rate  \
category           hired
Furniture Assembly 0      1.010970e+09  8.139054    39.463301
                   1      1.010678e+09  3.611888    38.701049
Mounting           0      1.011415e+09  8.065586    50.493961
                   1      1.011709e+09  4.596085    50.154804
Moving Help        0      1.010815e+09  8.095662    83.736345
                   1      1.011096e+09  4.145359    63.012259

                          num_completed_tasks
category           hired
Furniture Assembly 0               182.000212
                   1               249.020979
Mounting           0               216.470227
                   1               284.096085
Moving Help        0               256.616608
                   1               273.882662

In [35]:
#Based on the previous, how would you approach the question of:

#How can we use market data to suggest hourly rates to Taskers that would maximize their opportunity to be hired?

from sklearn.linear_model import LogisticRegression  # for Logistic Regression algorithm
from sklearn.cross_validation import train_test_split #to split the dataset for training and testing
from sklearn.neighbors import KNeighborsClassifier  # for K nearest neighbours
from sklearn import svm  #for Support Vector Machine (SVM) Algorithm
from sklearn import metrics #for checking the model accuracy
from sklearn.tree import DecisionTreeClassifier #for using Decision Tree Algoithm

In [36]:
#Q10 Applying different models on taskers hired using Hourly rate.

train, test = train_test_split(df, test_size = 0.3)

train_X = train[["hourly_rate"]]  # taking the training data features

train_y=train.hired     # output of our training data

test_X= test[["hourly_rate"]]   # taking test data features

test_y =test.hired


#Apply Logistic Regression Model

model = LogisticRegression()
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the Logistic Regression is',metrics.accuracy_score(prediction,test_y))



#Apply Decision Tree Model

model=DecisionTreeClassifier()
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the Decision Tree is',metrics.accuracy_score(prediction,test_y))



#Apply KNN Model

model=KNeighborsClassifier(n_neighbors=3) #this examines 3 neighbours for putting the new data into a class
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the KNN is',metrics.accuracy_score(prediction,test_y))



#Apply Support Vector Model

model = svm.SVC() #select the algorithm
model.fit(train_X,train_y) # we train the algorithm with the training data and the training output
prediction=model.predict(test_X) #now we pass the testing data to the trained algorithm
print('The accuracy of the SVM is:',metrics.accuracy_score(prediction,test_y))#now we check the accuracy of the algorithm. 
#we pass the predicted output by the model and the actual output

The accuracy of the Logistic Regression is 0.9453333333333334
The accuracy of the Decision Tree is 0.9454444444444444
The accuracy of the KNN is 0.9454444444444444
The accuracy of the SVM is: 0.9453333333333334

In [37]:
#Q10 Applying different models on taskers hired using num_completed_tasks.

train, test = train_test_split(df, test_size = 0.3)

train_X = train[["num_completed_tasks"]]# taking the training data features

train_y=train.hired# output of our training data

test_X= test[["num_completed_tasks"]] # taking test data features

test_y =test.hired


#Apply Logistic Regression Model

model = LogisticRegression()
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the Logistic Regression is',metrics.accuracy_score(prediction,test_y))



#Apply Decision Tree Model

model=DecisionTreeClassifier()
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the Decision Tree is',metrics.accuracy_score(prediction,test_y))



#Apply KNN Model

model=KNeighborsClassifier(n_neighbors=3) #this examines 3 neighbours for putting the new data into a class
model.fit(train_X,train_y)
prediction=model.predict(test_X)
print('The accuracy of the KNN is',metrics.accuracy_score(prediction,test_y))



#Apply Support Vector Model

model = svm.SVC() #select the algorithm
model.fit(train_X,train_y) # we train the algorithm with the training data and the training output
prediction=model.predict(test_X) #now we pass the testing data to the trained algorithm
print('The accuracy of the SVM is:',metrics.accuracy_score(prediction,test_y))#now we check the accuracy of the algorithm. 
#we pass the predicted output by the model and the actual output

The accuracy of the Logistic Regression is 0.9431111111111111
The accuracy of the Decision Tree is 0.9423333333333334
The accuracy of the KNN is 0.9296666666666666
The accuracy of the SVM is: 0.9426666666666667

In [38]:
df.groupby('hired').nunique()

,recommendation_id,created_at,tasker_id,position,hourly_rate,num_completed_tasks,hired,category
hired,,,,,,,,
0,2086,2079,824,15,82,953,1,3
1,1705,1702,312,15,59,464,1,3